services:
  - name: "My Pages"
    endpoints:
      - url: "https://www.burningash.cn"
      - url: "https://www.burningash.cn"
      - url: "https://www.burningash.cn"
      - url: "https://www.burningash.cn"
  - name: "My Services"
    endpoints:
      - url: "https://www.burningash.cn"
      - url: "https://www.burningash.cn"
      - url: "https://www.burningash.cn"
        status_code: 401
      - url: "https://www.burningash.cn"
